server:
  port: 8801
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/sendya/sweb-cloud-config
          search-paths: cloud-test-config
          username: 18x@loacg.com
          password:
      label: master